name: New Release

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build -e .

      - name: Read New Version
        id: package-version
        run: |
          echo "::set-output name=version::$(python -c 'from spyc.__version__ import __version__; print(__version__)')"

      - run: |
          python -m build
          gh release create "v${{ steps.package-version.outputs.version }}" \
            --notes-file CHANGELOG.md
